In [19]:
import numpy as np

docs = ['go pakistan',
'pakistan pakistan',
'hip hip hurray',
'jeetay ga bhai jeetay ga pakistan jeetay ga',
'pakistan zindabad',
'babar babar',
'rizwan rizwan',
'shaheen shaheen',
'imran khan zindabad',
'inquilab zindabad'
]

In [20]:
#from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token='<nothing>')

In [21]:
tokenizer.fit_on_texts(docs)

In [22]:
tokenizer.word_index

{'<nothing>': 1,
 'pakistan': 2,
 'jeetay': 3,
 'ga': 4,
 'zindabad': 5,
 'hip': 6,
 'babar': 7,
 'rizwan': 8,
 'shaheen': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'imran': 13,
 'khan': 14,
 'inquilab': 15}

In [23]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('pakistan', 5),
             ('hip', 2),
             ('hurray', 1),
             ('jeetay', 3),
             ('ga', 3),
             ('bhai', 1),
             ('zindabad', 3),
             ('babar', 2),
             ('rizwan', 2),
             ('shaheen', 2),
             ('imran', 1),
             ('khan', 1),
             ('inquilab', 1)])

In [24]:
tokenizer.document_count

10

In [7]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [6, 6, 11],
 [3, 4, 12, 3, 4, 2, 3, 4],
 [2, 5],
 [7, 7],
 [8, 8],
 [9, 9],
 [13, 14, 5],
 [15, 5]]

In [25]:
from keras.utils import pad_sequences

In [9]:
sequences = pad_sequences(sequences,padding='post')

In [26]:
sequences

array([[10,  2,  0,  0,  0,  0,  0,  0],
       [ 2,  2,  0,  0,  0,  0,  0,  0],
       [ 6,  6, 11,  0,  0,  0,  0,  0],
       [ 3,  4, 12,  3,  4,  2,  3,  4],
       [ 2,  5,  0,  0,  0,  0,  0,  0],
       [ 7,  7,  0,  0,  0,  0,  0,  0],
       [ 8,  8,  0,  0,  0,  0,  0,  0],
       [ 9,  9,  0,  0,  0,  0,  0,  0],
       [13, 14,  5,  0,  0,  0,  0,  0],
       [15,  5,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [27]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding, Flatten


In [12]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [29]:
X_train.shape

(25000, 50)

In [30]:
X_train

array([[ 2071,    56,    26, ...,    19,   178,    32],
       [ 8255,     5, 25249, ...,    16,   145,    95],
       [  215,    28,   610, ...,     7,   129,   113],
       ...,
       [    4,    65,   496, ...,     4,  3586, 22459],
       [   13,    18,    31, ...,    12,     9,    23],
       [ 7585,     8,  2197, ...,   204,   131,     9]], dtype=int32)

In [13]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [14]:
len(X_train[2])

141

In [15]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [16]:
X_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [17]:
model = Sequential()

model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 17ms/step - accuracy: 0.5029 - loss: 0.7190 - val_accuracy: 0.5004 - val_loss: 0.6941
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 19s 15ms/step - accuracy: 0.5003 - loss: 0.6933 - val_accuracy: 0.5049 - val_loss: 0.6943
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 16ms/step - accuracy: 0.5044 - loss: 0.6935 - val_accuracy: 0.5008 - val_loss: 0.6943
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - accuracy: 0.5068 - loss: 0.6930 - val_accuracy: 0.5028 - val_loss: 0.6954
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.5064 - loss: 0.6929 - val_accuracy: 0.5028 - val_loss: 0.6940
